#pragma once

#define NWFS_OK 0
#define NWFS_ERR_NO_INODE 1
#define NWFS_ERR_NOT_FILE 2
#define NWFS_ERR_NOT_DIR 3
#define NWFS_ERR_NO_SUCH_NAME 4
#define NWFS_ERR_NAME_ALREADY_EXISTS 5
#define NWFS_ERR_TOO_LARGE_FILE 6
#define NWFS_ERR_TOO_LARGE_DIR 7
#define NWFS_ERR_DIR_NOT_EMPTY 8
#define NWFS_ERR_TOO_LONG_NAME 9
#define NWFS_ERR_BAD_ARGUMENT 400
#define NWFS_ERR_SOCK_CREATE 701
#define NWFS_ERR_SOCK_CONNECT 702
#define NWFS_ERR_SOCK_SEND 703
#define NWFS_ERR_SOCK_RECV 704
#define NWFS_ERR_SOCK_NOK_HTTP 705
